import { ChangeDetectionStrategy, Component, computed, inject, signal } from '@angular/core';
import { Community, GroupRole } from '../../core/models/feed.models';
import { FeedApiService } from '../../core/services/feed-api.service';
import { CommunityCardComponent, CommunityFiltersComponent, CommunitySearchComponent, CreateCommunityButtonComponent, CreateCommunityModalComponent } from './community-shared.component';

@Component({ selector: 'app-my-communities', imports: [CommunitySearchComponent, CommunityFiltersComponent, CommunityCardComponent, CreateCommunityButtonComponent, CreateCommunityModalComponent], template: `<main class="community-page"><section class="page-heading"><div><h1>My Communities</h1><p>All the spaces where you connect, share, and belong.</p></div><app-create-community-button /></section><section class="controls"><app-community-filters [searchable]="false" [options]="roleFilters" [active]="activeRole()" (selected)="activeRole.set($event)" /><app-community-search placeholder="Search your communities..." (searchChanged)="search.set($event)" /></section>@if (loading()) { <p class="state">Loading your communities…</p> } @else if (!filtered().length) { <section class="empty"><span class="material-symbols-outlined">groups</span><h2>No communities found</h2><p>Join a community or create your own to get started.</p><app-create-community-button /></section> } @else { <section class="grid">@for (community of visible(); track community.id) { <app-community-card [community]="community" [showRole]="true" /> }</section>@if (filtered().length > visibleCount()) { <div class="load"><button type="button" (click)="visibleCount.update(value => value + 6)">Load More</button></div> } } </main><app-create-community-modal />`, styles: [`.community-page{min-height:100vh;margin-left:304px;padding:112px 40px 70px;max-width:1280px}.page-heading{display:flex;align-items:center;justify-content:space-between;gap:20px;margin-bottom:34px}.page-heading h1{margin:0 0 9px;font:800 2rem 'Plus Jakarta Sans',sans-serif}.page-heading p{margin:0;color:#584141}.controls{display:grid;gap:22px;margin-bottom:32px}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:24px}.state,.empty{text-align:center;color:#584141}.empty{display:grid;justify-items:center;gap:10px;padding:58px 24px;background:#fff0ef;border-radius:24px}.empty span{font-size:42px;color:#800020}.empty h2{margin:0;font-family:'Plus Jakarta Sans',sans-serif}.empty p{margin:0 0 10px}.load{text-align:center;margin:34px}.load button{border:1px solid #800020;border-radius:999px;background:transparent;padding:11px 28px;color:#800020;font-weight:700;cursor:pointer}.load button:hover{background:#800020;color:#fff}@media(max-width:1100px){.grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:760px){.community-page{margin:0;padding:88px 16px 96px}.page-heading{align-items:flex-start}.page-heading h1{font-size:1.65rem}.page-heading app-create-community-button{display:none}.grid{grid-template-columns:1fr}}`], changeDetection: ChangeDetectionStrategy.OnPush })
export class MyCommunitiesComponent {
  private readonly api = inject(FeedApiService); readonly loading = signal(true); readonly communities = signal<Community[]>([]); readonly activeRole = signal('all'); readonly search = signal(''); readonly visibleCount = signal(6);
  readonly roleFilters = [{ label: 'All', value: 'all' }, { label: 'Owner', value: 'owner' }, { label: 'Admin', value: 'admin' }, { label: 'Member', value: 'member' }];
  readonly filtered = computed(() => { const query = this.search().toLowerCase(); const role = this.activeRole(); return this.communities().filter((community) => { const current = String(community.currentUserRole).toLowerCase(); const numericRole = Number(community.currentUserRole ?? 0); const roleMatch = role === 'all' || (role === 'owner' && (numericRole === GroupRole.Owner || current === 'owner')) || (role === 'admin' && (numericRole === GroupRole.Admin || current === 'admin')) || (role === 'member' && (numericRole === GroupRole.Member || current === 'member')); return roleMatch && (!query || `${community.name} ${community.description || ''}`.toLowerCase().includes(query)); }); });
  readonly visible = computed(() => this.filtered().slice(0, this.visibleCount()));
  constructor() { this.api.getCommunities('', 100).subscribe({ next: (items) => { this.communities.set(items.filter((item) => item.currentUserRole !== null && item.currentUserRole !== undefined)); this.loading.set(false); }, error: () => this.loading.set(false) }); }
}
